baseURL = "https://shenghuaxia36-source.github.io/myweb/"
languageCode = "en-us"
title = "Gourney Of oG-Go"

theme = "ananke"

[params]
  # 修复了这里的全角中文双引号 “ 变成半角 "
  mainSections = ["technology", "ai", "life", "posts","about"]

  site_logo = ""
  description = "My Web"

[menus]

  [[menus.main]]
    name = "Technology"
    pageRef = "/technology"
    weight = 10

  [[menus.main]]
    name = "AI"
    pageRef = "/ai"
    weight = 20

  [[menus.main]]
    name = "Life"
    pageRef = "/life"
    weight = 30

  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 40

  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 50